### ISSUE TITLE
Code split out by chapter?

### ISSUE THREAD

**Issue by tylercollier** [sf105/goos-code#2]
Hi there,

As far as I can tell, the code here is the final code, and is not split out by chapter, which would be much more helpful and as is common in most programming books.  Am I missing something?  I looked in the commit logs and see only 3, the first being the "final" code.  I was hoping to see some tags like "Chapter 1", "Chapter 2", etc.

Is there any way you could split out the code by chapter?

Thanks,
Ty

**Comment by sf105** [comment]
I'm sure someone's done this, but we haven't referenced it. I suggest you post this question on the #goos mailing list. If not, then we ought to...

**Comment by tylercollier** [comment]
How could someone have done this?  That's my whole point, it can't be done.  All the code was checked into github at the end.  Even if someone on the #goos mailing list knows (I'll try to find that), I think it should be posted or linked here.

**Comment by sf105** [comment]
I believe they worked it out for themselves and checked in regularly. It should be linked here. I just don't have an example handy.
