### ISSUE TITLE
Missing unit tests for XMPPAuction and XMPPAuctionHouse?

### ISSUE THREAD

**Issue by qertoip** [sf105/goos-code#3]
Cannot find unit tests for non-trivial classes XMPPAuction and XMPPAuctionHouse.

**Comment by gmoeck** [comment]
Those would be integration tests, which you can see the auction house test [here](https://github.com/sf105/goos-code/blob/master/test/integration/test/integration/auctionsniper/xmpp/XMPPAuctionHouseTest.java)

**Comment by sf105** [comment]
What Greg said
